FROM amazonlinux:2

RUN yum install -y gcc git tar gzip make glibc-devel && \
    curl -LO https://go.dev/dl/go1.22.3.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.22.3.linux-amd64.tar.gz

ENV PATH="/usr/local/go/bin:$PATH"

WORKDIR /app

COPY . .

RUN GOOS=linux GOARCH=amd64 go build -o bootstrap main.go